config/routes.rb
Rails.application.routes.draw do
  resources :visits do
    resource :comments
  end

  resources :subjects

  root 'subjects#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base

  has_many :visits

  validates :subjectNumber, presence: true,
            length: { minimum: 8}
  validates :age, presence: true

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :subject
  has_many :comments

  validates :dov, presence: true
  validates :subject_id, presence: true

end

app/models/visit1.rb
class Visit1 < ActiveRecord::Base
  belongs_to :visit


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to new_visit_path, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subjectNumber, :age)
    end
end

app/controllers/visit1s_controller.rb
class Visit1sController < ApplicationController

  def create

    @visit = Visit.find(params[:visit_id])

    @visit1 = @visit.comments.create(comment_params)

    redirect_to visit_path(@visit)

  end


  private
  def comment_params

    params.require(:visit1).permit(:icfdt, :dov1, :sex)

  end



end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:dov, :subject_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/visit1s_helper.rb
module Visit1sHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subjectNumber %><br>
    <%= f.text_field :subjectNumber %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Register a New Subject</h1>

<table>
  <thead>
    <tr>
      <th>Subject Number</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subjectNumber %></td>
        <td><%= subject.age %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>
<%= link_to 'Visit 1', visits_path  %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject Number:</strong>
  <%= @subject.subjectNumber %>
</p>

<p>
  <strong>Age:</strong>
  <%= @subject.age %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dov %><br>
    <%= f.text_field :dov %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create Visit 1</h1>
<table>
  <thead>
    <tr>
      <th>Dov</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.dov %></td>
        <td><%= visit.subject_id %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>Visit 1</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dov:</strong>
  <%= @visit.dov %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @visit.subject_id %>
</p>


<h2>Comments</h2>

<% @visit.comments.each do |comment|  %>

    <p>
      <strong>Commenter</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong>Comment</strong>
      <%= comment.body %>
    </p>
<% end %>

<h2>Add a Comment:</h2>

<%= form_for([@visit, @visit.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %>
      <%= f.text_field :commenter %>
    <p>

    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>



<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>